# Minimal Working Enhanced Thermal Printer Configuration
# Phase 1 Implementation - Core Features Only

esphome:
  name: thermal_printer_enhanced
  friendly_name: Enhanced Thermal Printer
  platform: ESP8266
  board: d1_mini

# WiFi Configuration
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  
  ap:
    ssid: "ThermalPrinter-Enhanced"
    password: "thermalprint123"

captive_portal:

# Logging
logger:
  level: INFO
  logs:
    thermal_printer: DEBUG

ota:
  - platform: esphome
    password: !secret ota_password

# External Components
external_components:
  - source:
      type: local
      path: my_components

# UART Configuration
uart:
  id: thermal_uart
  tx_pin: GPIO4  # D2 on D1 Mini
  rx_pin: GPIO0  # D3 on D1 Mini  
  baud_rate: 9600
  data_bits: 8
  parity: NONE
  stop_bits: 1

# Enhanced Home Assistant API with working Phase 1 services
api:
  encryption:
    key: !secret api_encryption_key
  
  # Core working services for Phase 1
  actions:
    # Enhanced text printing with rotation support
    - action: print_text
      variables:
        message: string
        text_size: string
        alignment: string
        bold: bool
        underline: bool
        inverse: bool
        rotation: int  # 0=normal, 1=90°, 2=180°, 3=270°
      then:
        - lambda: |-
            auto printer = id(my_thermal_printer);
            
            // Set text formatting
            if (text_size == "S" || text_size == "small") {
              printer->set_text_size(1);
            } else if (text_size == "M" || text_size == "medium") {
              printer->set_text_size(2);
            } else if (text_size == "L" || text_size == "large") {
              printer->set_text_size(3);
            }
            
            // Set justification
            if (alignment == "L" || alignment == "left") {
              printer->justify('L');
            } else if (alignment == "C" || alignment == "center") {
              printer->justify('C');
            } else if (alignment == "R" || alignment == "right") {
              printer->justify('R');
            }
            
            // Set formatting
            printer->bold_on(bold);
            printer->underline_on(underline);
            printer->inverse_on(inverse);
            
            // Handle rotation
            if (rotation > 0) {
              printer->print_rotated_text(message.c_str(), rotation);
            } else {
              printer->print_text(message.c_str());
              printer->println();
            }
            
            // Reset formatting
            printer->bold_off();
            printer->underline_off();
            printer->inverse_off();
            printer->justify('L');

    # 90-degree rotated text printing
    - action: print_rotated_text
      variables:
        message: string
        rotation: int  # 1=90°, 2=180°, 3=270°
      then:
        - lambda: |-
            auto printer = id(my_thermal_printer);
            printer->print_rotated_text(message.c_str(), rotation);

    # QR Code printing
    - action: print_qr_code
      variables:
        data: string
        size: int  # 1-4 (small to extra large)
        error_correction: int  # 0=Low, 1=Medium, 2=Quartile, 3=High
        label: string  # Optional label above QR code
      then:
        - lambda: |-
            auto printer = id(my_thermal_printer);
            if (!label.empty()) {
              printer->justify('C');
              printer->set_text_size(1);
              printer->print_text(label.c_str());
              printer->feed(1);
            }
            printer->print_qr_code(data.c_str(), size, error_correction);

    # Enhanced two-column printing
    - action: print_two_column
      variables:
        left_text: string
        right_text: string
        fill_dots: bool
        text_size: string
      then:
        - lambda: |-
            auto printer = id(my_thermal_printer);
            char size_char = 'S';
            if (text_size == "M" || text_size == "medium") size_char = 'M';
            else if (text_size == "L" || text_size == "large") size_char = 'L';
            
            printer->print_two_column(left_text.c_str(), right_text.c_str(), 
                                     fill_dots, size_char);

    # Simple receipt printing
    - action: print_receipt
      variables:
        business_name: string
        total: string
      then:
        - lambda: |-
            auto printer = id(my_thermal_printer);
            printer->print_simple_receipt(business_name.c_str(), total.c_str());

    # Simple shopping list
    - action: print_shopping_list
      variables:
        items: string
      then:
        - lambda: |-
            auto printer = id(my_thermal_printer);
            printer->print_shopping_list(items.c_str());

    # Safe printing with error checking
    - action: safe_print_text
      variables:
        message: string
      then:
        - lambda: |-
            auto printer = id(my_thermal_printer);
            auto result = printer->safe_print_text(message.c_str());
            
            // Log the result
            if (result == PrintResult::SUCCESS) {
              ESP_LOGI("thermal_printer", "Print successful");
            } else {
              ESP_LOGW("thermal_printer", "Print failed - check paper/printer status");
            }

    # Existing basic services
    - action: print_barcode
      variables:
        barcode_type: int
        barcode_data: string
      then:
        - lambda: |-
            auto printer = id(my_thermal_printer);
            printer->print_barcode(barcode_type, barcode_data.c_str());

    - action: feed_paper
      variables:
        lines: int
      then:
        - lambda: |-
            auto printer = id(my_thermal_printer);
            printer->feed(lines);

    - action: wake_printer
      then:
        - lambda: |-
            auto printer = id(my_thermal_printer);
            printer->wake();

    - action: sleep_printer
      then:
        - lambda: |-
            auto printer = id(my_thermal_printer);
            printer->sleep();

    - action: test_print
      then:
        - lambda: |-
            auto printer = id(my_thermal_printer);
            printer->test();

    - action: reset_paper_usage
      then:
        - lambda: |-
            auto printer = id(my_thermal_printer);
            printer->reset_paper_usage();

    - action: set_paper_roll_length
      variables:
        length_mm: float
      then:
        - lambda: |-
            auto printer = id(my_thermal_printer);
            printer->set_paper_roll_length(length_mm);

    # Error recovery
    - action: recover_printer
      then:
        - lambda: |-
            auto printer = id(my_thermal_printer);
            printer->recover_from_error();



# Enhanced Thermal Printer Component with Phase 1 Features
thermal_printer:
  id: my_thermal_printer
  uart_id: thermal_uart
  paper_roll_length: 30000
  line_height_calibration: 4.0
  enable_rotation: true
  enable_qr_codes: true
  startup_message: true

# Text Sensors
text_sensor:
  - platform: thermal_printer
    thermal_printer_id: my_thermal_printer
    name: "Paper Status"
    id: paper_status

  # Simple printer status
  - platform: template
    name: "Printer Status"
    id: printer_status_simple
    lambda: |-
      auto printer = id(my_thermal_printer);
      if (printer->has_paper()) {
        return std::string("Ready - Paper OK");
      } else {
        return std::string("Paper Out");
      }
    update_interval: 30s

# Binary Sensors
binary_sensor:
  - platform: thermal_printer
    thermal_printer_id: my_thermal_printer
    name: "Paper Loaded"
    id: paper_loaded
    # Removed device_class: paper (doesn't exist)

  # Simple printer online check
  - platform: template
    name: "Printer Online"
    id: printer_online
    device_class: connectivity
    lambda: |-
      return id(my_thermal_printer)->has_paper(); // Simplified check
    # Removed update_interval (binary_sensor doesn't support it)

# Sensors
sensor:
  - platform: uptime
    name: "Uptime"

  - platform: wifi_signal
    name: "WiFi Signal"
    update_interval: 60s

  # Usage sensors
  - platform: template
    name: "Paper Usage (mm)"
    id: paper_usage_mm
    icon: mdi:ruler
    unit_of_measurement: "mm"
    accuracy_decimals: 1
    state_class: total_increasing
    lambda: |-
      return id(my_thermal_printer)->get_paper_usage_mm();
    update_interval: 30s

  - platform: template
    name: "Paper Usage (%)"
    id: paper_usage_percent
    icon: mdi:percent
    unit_of_measurement: "%"
    accuracy_decimals: 1
    lambda: |-
      return id(my_thermal_printer)->get_paper_usage_percent();
    update_interval: 30s

  - platform: template
    name: "Lines Printed"
    id: lines_printed
    icon: mdi:format-line-spacing
    state_class: total_increasing
    lambda: |-
      return id(my_thermal_printer)->get_lines_printed();
    update_interval: 30s

  - platform: template
    name: "Characters Printed"
    id: characters_printed
    icon: mdi:alphabetical
    state_class: total_increasing
    lambda: |-
      return id(my_thermal_printer)->get_characters_printed();
    update_interval: 30s

  # Performance metrics
  - platform: template
    name: "Characters Per Minute"
    id: chars_per_minute
    icon: mdi:speedometer
    unit_of_measurement: "chars/min"
    accuracy_decimals: 1
    lambda: |-
      uint32_t uptime_minutes = millis() / 60000;
      if (uptime_minutes > 0) {
        return (float)id(my_thermal_printer)->get_characters_printed() / uptime_minutes;
      }
      return 0.0f;
    update_interval: 60s

  - platform: template
    name: "Paper Remaining (mm)"
    id: paper_remaining_mm
    icon: mdi:tape-measure
    unit_of_measurement: "mm"
    accuracy_decimals: 0
    lambda: |-
      float used = id(my_thermal_printer)->get_paper_usage_mm();
      float total = 30000.0; // 30m default roll
      return std::max(0.0f, total - used);
    update_interval: 30s

# Status LED
status_led:
  pin:
    number: GPIO2
    inverted: true

# Switches
switch:
  - platform: template
    name: "Printer Wake"
    id: printer_wake_switch
    icon: mdi:power
    optimistic: true
    turn_on_action:
      - lambda: |-
          id(my_thermal_printer)->wake();
    turn_off_action:
      - lambda: |-
          id(my_thermal_printer)->sleep();

# Number Controls
number:
  - platform: template
    name: "Line Spacing"
    id: line_spacing
    icon: mdi:format-line-spacing
    min_value: 24
    max_value: 64
    initial_value: 32
    step: 1
    mode: box
    optimistic: true
    set_action:
      - lambda: |-
          id(my_thermal_printer)->set_line_height(x);

# Select Controls
select:
  - platform: template
    name: "Default Text Size"
    id: default_text_size
    icon: mdi:format-size
    optimistic: true
    options:
      - "Small"
      - "Medium" 
      - "Large"
    initial_option: "Medium"
    set_action:
      - lambda: |-
          auto printer = id(my_thermal_printer);
          if (x == "Small") {
            printer->set_text_size(1);
          } else if (x == "Medium") {
            printer->set_text_size(2);
          } else if (x == "Large") {
            printer->set_text_size(3);
          }

# Button Controls
button:
  - platform: template
    name: "Print Test Page"
    id: test_page_button
    icon: mdi:printer-check
    on_press:
      - lambda: |-
          auto printer = id(my_thermal_printer);
          printer->test_page();

  - platform: template
    name: "Print Separator Line"
    id: separator_button
    icon: mdi:minus
    on_press:
      - lambda: |-
          auto printer = id(my_thermal_printer);
          printer->justify('C');
          printer->print_text("================================");
          printer->feed(1);
          printer->justify('L');

# Web Server
web_server:
  port: 80
  version: 2
